# Generated by Django 5.1.5 on 2025-01-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('-criado_em',), 'verbose_name_plural': 'Produtos'},
        ),
    ]
